#!/usr/bin/env bash
# Author: Ruslan Ulanov
# Description: Dump multiple concatenated certs from one file
# Usage: cat-pems-in-file file.pem
CERT_CHAIN=$1
FILTER=$2
if [ -z ${CERT_CHAIN} ]; then 
    echo "ERROR: Missing PEM file path. Usage: $(basename $0) file.pem "
    exit 1
else
    echo "* File: ${CERT_CHAIN}"
    CERTS=$( openssl crl2pkcs7 -nocrl -certfile "${CERT_CHAIN}" | openssl pkcs7 -print_certs -text -noout )
    if [ -z "${FILTER}" ]; then
        echo "${CERTS}"
    else
        echo "${CERTS}" | grep "${FILTER}"
    fi
fi
